spring:
  application:
    name: spring-boot-admin-sample-war
  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  endpoints:
    web:
      expose: "*"
  endpoint:
    health:
      show-details: true